---
title: "More SiSyn forest plots"
author: "Patrick Thomas"
date: "November 22 2021"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    collapsed: false
---


# Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(tidyverse)
library(knitr)
library(psych)
library(cowplot)
library(ggpubr)

theme_set(theme_bw()+
            theme(axis.text=element_text(size=8),
  axis.title.x = element_text(size = 16),
  axis.title.y = element_text(size = 16)))

knitr::opts_chunk$set(fig.width=12, fig.height=8, 
                      fig.path='Figs/Effect sizes and forest plots/', 
                      echo=TRUE, warning=FALSE, message=FALSE)

jevergreen <- "#218D3A"
jever2color <- c("#218D3A", "#E2C171")

jever3color <- c("#E2C171","#218D3A", "#297C8C")

jever4color <- c("#297C8C", "#5792D0", "#116D2B", "#E2C171")

jever4color_andblack <- c("#297C8C", "#5792D0", "#116D2B", "#E2C171", "black")

select <- dplyr::select


```

> read in data and have a look at the data summary

```{r}

site_info <- read_csv("SiteCharacteristics_PCA_WRTDS_112221.csv") %>% 
  rename(site = SITE, LTER = LTER.x) %>%
  mutate(log_drainage = log(drainSqKm))

wrtds <- read_csv("Si_EGRETCi_Trends_slopes_090721.csv")

percent_change <- read_csv("WRTDS_Pct_Change_Wide.csv")

wrtds <- left_join(wrtds, site_info)

wrtds <- left_join(wrtds, percent_change)

summary(wrtds)
describe(wrtds)

```


# a first plot to look at the raw data 

```{r}

#Effect sizes of concentration change
ggplot(wrtds, aes(x = site, y = estC, ymin = lowC95, ymax = upC95))+
  geom_pointrange()+
  coord_flip()+
  geom_hline(yintercept = 0)+
  scale_x_discrete(limits = rev)+
  facet_wrap(~LTER, scales='free')


#Effect sizes of flux change
ggplot(wrtds, aes(x = site, y = estF, ymin = lowC95, ymax = upC95))+
  geom_pointrange()+
  coord_flip()+
  geom_hline(yintercept = 0)+
  scale_x_discrete(limits = rev)+
  facet_wrap(~LTER, scales='free')


```

# plots sorted by effect size of DSi conc and flux (these are trimmed to exclude huge CI values)

```{r}

wrtds %>%
  #mutate(LTER_site = paste(LTER, site, sep = "_")) %>% 
  ggplot(aes(fill = estC, x = fct_reorder(site, estC), y = estC, ymin = lowC95, ymax=upC95))+
  geom_pointrange(color="black", shape = 21, size = 1)+
  #scale_x_discrete(limits = rev)+
  coord_flip()+
  geom_hline(yintercept = 0, linetype="dashed")+
  theme(axis.text=element_text(size=12))+
  ylim(-10, 10)+
  xlab("site")+
  ylab("DSi change slope")

wrtds %>%
  #mutate(LTER_site = paste(LTER, site, sep = "_")) %>% 
  ggplot(aes(fill = estF, x = fct_reorder(site, estF), y = estF, ymin = lowC95, ymax=upC95))+
  geom_pointrange(color="black", shape = 21, size = 1)+
  #scale_x_discrete(limits = rev)+
  coord_flip()+
  geom_hline(yintercept = 0, linetype="dashed")+
  theme(axis.text=element_text(size=16))+
  ylim(-10, 10)+
  xlab("site")+
  ylab("DSi flux change slope")

```


# arranged by drainage area

```{r}

A <- wrtds %>%
  #mutate(LTER_site = paste(LTER, site, sep = "_")) %>% 
  ggplot(aes(fill = drainSqKm, x = fct_reorder(site, drainSqKm), y = estC, ymin = lowC95, ymax=upC95))+
  geom_pointrange(color="black", shape = 21, size = 2)+
  #scale_x_discrete(limits = rev)+
  coord_flip()+
  geom_hline(yintercept = 0, linetype="dashed")+
  theme(axis.text=element_text(size=16))+
  ylim(-10, 10)+
  xlab("site")+
  theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())+
  ylab("DSi change slope")
A

B <- wrtds %>%
  #mutate(LTER_site = paste(LTER, site, sep = "_")) %>% 
  ggplot(aes(fill = drainSqKm, x = fct_reorder(site, drainSqKm), y = estF, ymin = lowC95, ymax=upC95))+
  geom_pointrange(color="black", shape = 21, size = 2)+
  #scale_x_discrete(limits = rev)+
  coord_flip()+
  geom_hline(yintercept = 0, linetype="dashed")+
  theme(axis.text=element_text(size=16))+
  ylim(-10, 10)+
  xlab("site")+
    theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())+
  ylab("DSi flux change slope")
B

plot_grid(A,B)

ggplot(wrtds, aes(drainSqKm, estC))+
  geom_point()

```

# ordered by drainage area and faceted by biome

```{r}

A <- wrtds %>%
  #mutate(LTER_site = paste(LTER, site, sep = "_")) %>% 
  ggplot(aes(fill = drainSqKm, x = fct_reorder(site, drainSqKm), y = estC, ymin = lowC95, ymax=upC95))+
  geom_pointrange(color="black", shape = 21, size = 2)+
  #scale_x_discrete(limits = rev)+
  coord_flip()+
  geom_hline(yintercept = 0, linetype="dashed")+
  theme(axis.text=element_text(size=16))+
  ylim(-10, 10)+
  xlab("site")+
  facet_wrap(~Biome, scales = "free")+
      theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())+
  ylab("DSi change slope")
A

B <- wrtds %>%
  #mutate(LTER_site = paste(LTER, site, sep = "_")) %>% 
  ggplot(aes(fill = drainSqKm, x = fct_reorder(site, drainSqKm), y = estF, ymin = lowC95, ymax=upC95))+
  geom_pointrange(color="black", shape = 21, size = 2)+
  #scale_x_discrete(limits = rev)+
  coord_flip()+
  geom_hline(yintercept = 0, linetype="dashed")+
  theme(axis.text=element_text(size=16))+
  ylim(-10, 10)+
  xlab("site")+
  facet_wrap(~Biome, scales = "free")+
      theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())+
  ylab("DSi flux change slope")
B

plot_grid(A,B)


```

# ordered by log(drainage area) and faceted by biome

```{r}

A <- wrtds %>%
  #mutate(LTER_site = paste(LTER, site, sep = "_")) %>% 
  ggplot(aes(fill = log_drainage, x = fct_reorder(site, log_drainage), y = estC, ymin = lowC95, ymax=upC95))+
  geom_pointrange(color="black", shape = 21, size = 1.5)+
  #scale_x_discrete(limits = rev)+
  coord_flip()+
  geom_hline(yintercept = 0, linetype="dashed")+
  theme(axis.text=element_text(size=16))+
  ylim(-10, 10)+
  xlab("site")+
  facet_wrap(~Biome, scales = "free")+
      theme(axis.title.y = element_blank(),
            legend.position = "top",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())+
  scale_fill_viridis_c()+
  #scale_fill_continuous(low = "khaki", high =  "firebrick")+
  ylab("DSi change slope")
A

B <- wrtds %>%
  #mutate(LTER_site = paste(LTER, site, sep = "_")) %>% 
  ggplot(aes(fill = log_drainage, x = fct_reorder(site, log_drainage), y = estF, ymin = lowC95, ymax=upC95))+
  geom_pointrange(color="black", shape = 21, size = 1.5)+
  #scale_x_discrete(limits = rev)+
  coord_flip()+
  geom_hline(yintercept = 0, linetype="dashed")+
  theme(axis.text=element_text(size=16))+
  ylim(-10, 10)+
  xlab("site")+
  facet_wrap(~Biome, scales = "free")+
      theme(axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())+
  scale_fill_viridis_c()+
  #scale_fill_continuous(low = "khaki", high =  "firebrick")+
  ylab("DSi flux change slope")
B

plot_grid(A,B)


```


# arranged and colored by biome with size showing drainage area

```{r}


A <- wrtds %>%
  #mutate(LTER_site = paste(LTER, site, sep = "_")) %>% 
  ggplot(aes(fill = Biome, x = fct_reorder(site, Biome), y = estC, ymin = lowC95, ymax=upC95))+
  geom_pointrange(color="black", shape = 21, aes(size = log_drainage))+
  #scale_x_discrete(limits = rev)+
  coord_flip()+
  geom_hline(yintercept = 0, linetype="dashed")+
  theme(axis.text=element_text(size=16))+
  scale_size_continuous(range = c(.5, 1.5))+
  ylim(-10, 10)+
  xlab("site")+
  #facet_wrap(~Biome, scales = "free")+
      theme(axis.title.y = element_blank(),
            legend.position = "top",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())+
  #scale_fill_viridis_c()+
  guides(size = "none")+
  scale_fill_brewer(palette = "Paired")+
  #scale_fill_continuous(low = "khaki", high =  "firebrick")+
  ylab("DSi change slope")



B <- wrtds %>%
  #mutate(LTER_site = paste(LTER, site, sep = "_")) %>% 
  ggplot(aes(fill = Biome, x = fct_reorder(site, Biome), y = estF, ymin = lowC95, ymax=upC95))+
  geom_pointrange(color="black", shape = 21, aes(size = log_drainage))+
  #scale_x_discrete(limits = rev)+
  coord_flip()+
  geom_hline(yintercept = 0, linetype="dashed")+
  theme(axis.text=element_text(size=16))+
  scale_size_continuous(range = c(.5, 1.5))+
  ylim(-10, 10)+
  xlab("site")+
  #facet_wrap(~Biome, scales = "free")+
      theme(axis.title.y = element_blank(),
            legend.position = "top",
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank())+
  #scale_fill_viridis_c()+
  guides(size = "none")+
  scale_fill_brewer(palette = "Paired")+
  #scale_fill_continuous(low = "khaki", high =  "firebrick")+
  ylab("DSi flux change slope")

ggarrange(A, B, common.legend = TRUE)

```



```{r}



```









